### PR TITLE
Add support for AssistNow

### PR DESCRIPTION
**Pull request by Vagabond**
Additionally, add partial support for CFG-NAV5 polling

### CODE REVIEW

**Comment by fvasquez** [comment]
Since offline assistance doesn't appear to help I will open another PR for online assistance.

**Comment by Vagabond** [comment]
It's worth trying to validate it better, I think, but we should also try to do online assistance.

**Comment by fvasquez** [comment]
```
# erl -pa /home/helium -pz lib/*/ebin
Erlang/OTP 21 [erts-10.1] [source] [smp:2:2] [ds:2:2:10] [async-threads:1]
   
Eshell V10.1  (abort with ^G)
1> application:ensure_all_started(ubx).
{ok,[erlang_ale,ubx]}
2> {ok, Pid} = ubx:start_link("spidev1.0", 68, [], self()).
Sending b5 62 6 13 4 0 0 0 f0 39 46 e6
Sending b5 62 6 0 14 0 4 0 c1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 e1 38
Sending b5 62 6 31 20 0 0 1 0 0 0 0 0 0 1 0 0 0 0 12 7a 0 0 0 0 0 0 0 0 0 0 0 0 0 6f 8 0 0 5c c0
Sending b5 62 6 23 28 0 2 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 58 74
Sending b5 62 6 9 d 0 0 0 0 0 ff ff 0 0 0 0 0 0 17 31 bf
{ok,<0.85.0>}
error timeout
error timeout
error timeout
error timeout
error timeout
3> ubx:upload_offline_assistance(Pid, "/root/offline.ubx").
...
Sending b5 62 13 20 4c 0 0 0 18 6 13 2 7 c f7 7 bc fd 0 e0 fd bf e3 ff f d8 1c cb be f7 97 b4 e0 e3 18 7 5 5b 35 4b c 9 fc 67 f4 1c d 18 c4 f 5b 45 1 e0 b1 cd d2 91 13 1c df d9 bb 84 df f7 92 b9 15 1d e0 dc 48 fa bd fd d8 c9 0 0 0 0 3e 78
ok
Type 1 InfoCode 0 MsgID 32 MsgPayloadStart <<0,0,20,6>>
error timeout
Type 1 InfoCode 0 MsgID 32 MsgPayloadStart <<0,0,21,6>>
error timeout
Type 0 InfoCode 4 MsgID 32 MsgPayloadStart <<0,0,22,6>>
error timeout
Type 0 InfoCode 4 MsgID 32 MsgPayloadStart <<0,0,23,6>>
error timeout
Type 0 InfoCode 4 MsgID 32 MsgPayloadStart <<0,0,24,6>>
```

**Review by fvasquez — APPROVED** [review]
I am now getting a corresponding UBX-MGA-ACK-DATA0 acceptance message back from the GPS receiver for every data assistance message I am sending over SPI.

**Pull request merged**
